apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kvcc-components
  labels:
    cloud.googleapis.com/location: us-east1
spec:
  template:
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: us-east1-docker.pkg.dev/baby-stats-10331/images/kvcc-components:latest
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
  traffic:
    - percent: 100
      latestRevision: true
