name: storybook-cloudrun

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: baby-stats-10331
  IMAGE_URL: us-east1-docker.pkg.dev/baby-stats-10331/images/kvcc-components

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set commit sha
        run: echo "COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: set image tags
        run: |-
          echo "TAG_LATEST=${{ env.IMAGE_URL }}:latest" >> $GITHUB_ENV
          echo "TAG_COMMIT=${{ env.IMAGE_URL }}:${{ env.COMMIT }}" >> $GITHUB_ENV

      - name: authorize gcloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: setup gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: docker login
        run: gcloud auth configure-docker us-east1-docker.pkg.dev

      - name: build image
        run: |-
          docker build \
            -t ${{ env.TAG_COMMIT }} \
            -t ${{ env.TAG_LATEST }} \
            .

      - name: push image
        run: docker push --all-tage ${{ env.IMAGE_URL }}

      - name: update service.yml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: service.yml
          propertyPath: spec.template.spec.containers[0].image
          value: ${{ env.TAG_COMMIT }}
          commitChange: false
          updateFile: true

      - name: upload service.yml artifact
        uses: actions/upload-artifact@v3
        with:
          name: service.${{ env.COMMIT }}.yml
          path: service.yml

      - name: replace service
        run: gcloud run services replace --quiet service.yml
