name: storybook-cloudrun

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: baby-stats-10331
  IMAGE_URL: us-east1-docker.pkg.dev/baby-stats-10331/images/kvcc-components:latest

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: authorize gcloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: setup gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: docker login
        run: gcloud auth configure-docker us-east1-docker.pkg.dev

      - name: build image
        run: docker build -t ${{ env.IMAGE_URL }} .

      - name: push image
        run: docker push ${{ env.IMAGE_URL }}

      - name: update service
        run: gcloud run services replace --quiet service.yml
